- .travis.yml
> chore: activate travis deployment

- server/db/models/index.js
- server/db/models/location.js
- server/db/models/location.spec.js
* [x ] added unit tests (or none needed)
---
> Model location

- server/db/models/content.js
- server/db/models/content.spec.js
- server/db/models/index.js
> feat: content model resolves #4

- script/seed.js
- server/db/models/apiSource.js
- server/db/models/apiSource.spec.js
- server/db/models/index.js
> feat: created apiSource model, updated seed, and created apiSource model test

- package-lock.json
- package.json
- server/api/index.js
- server/api/meetups.js
> Meetup route

- package-lock.json
- package.json
- server/api/index.js
- server/api/newsapi.js
- server/db/models/content.spec.js
> fix: trying second PR for Newsapi

- client/app.js
- client/components/Landing.js
- client/components/index.js
- client/index.js
- client/routes.js
- public/index.html
> Feat: Landing component

- server/api/newsapi.js
- server/db/models/content.js
> feat: newsapi send to db resolves #33

- server/api/meetups.js
* [ x] written relevant docs (or none needed)
---
> Meetup database connect

- client/components/Landing.js
- client/components/auth-form.js
- client/components/index.js
- client/components/navbar.js
- client/store/user.js
- client/store/user.spec.js
- public/style.css
- server/auth/google.js
- server/auth/index.js
> Feat: Updated Navbar

- .travis.yml
- script/seed.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/apiSource.js
- server/db/models/index.js
- server/db/models/location.js
- server/db/models/location.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
> fix;Model updates

- client/index.js
> fix: lowercase app for deployment bug

- server/api/interest.js
> feat: add route to get all interests from db resolves #51

- server/api/index.js
> fix: add interest route to api index

- .travis.yml
> fix: edit to app name in travis config file

- server/api/interests.js
> fix: add where clause to interest route

- client/store/content.js
- server/api/content.js
- server/api/index.js
> feat: content reducer and api route

- client/components/Carousel.js
- client/components/Landing.js
- client/store/index.js
> feat: Wiring components to backend

- client/components/Carousel.js
- client/components/Landing.js
- client/store/index.js
> fix: comment out unfinished code

- client/components/Navbar.js
* [ x] written relevant docs (or none needed)
* [c ] referenced any relevant issues (or none exist)
---
> feat: Navbar UI resolved

- client/store/content.js
- server/api/content.js
> fix: Content component error

- client/components/Landing.js
> feat: landing page picking interests from db

- client/components/Carousel.js
- client/components/InterestPage.js
> feat: working carousel

- client/components/Carousel.js
- client/components/InterestPage.js
- client/components/Landing.js
- client/components/Navbar.js
- public/style.css
> fix: carousel and nav uniformity with Material UI

- client/components/Landing.js
> feat: added welcome to landing if user logged in

- script/dataAggregator.js
[x] set variable and hard coded deployment path for api calls
> fix: hard-coded production deployment server for api calls resolves #141

- client/components/InterestPage.js
- public/index.html
- public/style.css
> fix: background color

- script/dataAggregator.js
- script/seed.js
- server/api/meetups.js
> fix: meetup api, and seed file

- server/api/search.js
> fix: search api server

- client/components/Carousel.js
- client/components/InterestPage.js
- client/components/Navbar.js
- public/style.css
> fix: better design

- public/index.html
> fix: page title

- client/components/CarouselCard.js
> fix: card styling 

- client/components/SavedCarouselCard.js
> fix: saved carousel card
